CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `root`@`127.0.0.1` 
    SQL SECURITY DEFINER
VIEW `wp_cb2_view_sequence_num` AS
    SELECT 0 AS `num` 
    UNION ALL SELECT 1 AS `1` 
    UNION ALL SELECT 2 AS `2` 
    UNION ALL SELECT 3 AS `3` 
    UNION ALL SELECT 4 AS `4` 
    UNION ALL SELECT 5 AS `5` 
    UNION ALL SELECT 6 AS `6` 
    UNION ALL SELECT 7 AS `7` 
    UNION ALL SELECT 8 AS `8` 
    UNION ALL SELECT 9 AS `9`