CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `root`@`127.0.0.1` 
    SQL SECURITY DEFINER
VIEW `wp_cb2_view_calendar_day_posts` AS
    SELECT 
        NULL AS `ID`,
        1 AS `post_author`,
        `sq`.`datetime_start` AS `post_date`,
        `sq`.`datetime_start` AS `post_date_gmt`,
        '' AS `post_content`,
        'available' AS `post_title`,
        '' AS `post_excerpt`,
        'publish' AS `post_status`,
        'closed' AS `comment_status`,
        'closed' AS `ping_status`,
        '' AS `post_password`,
        'available' AS `post_name`,
        '' AS `to_ping`,
        '' AS `pinged`,
        `sq`.`datetime_end` AS `post_modified`,
        `sq`.`datetime_end` AS `post_modified_gmt`,
        '' AS `post_content_filtered`,
        NULL AS `post_parent`,
        '' AS `guid`,
        0 AS `menu_order`,
        'periodoccurrence' AS `post_type`,
        '' AS `post_mime_type`,
        0 AS `comment_count`,
        NULL AS `period_id`,
        0 AS `recurrence_index`,
        NULL AS `timeframe_ID`,
        NULL AS `location_ID`,
        NULL AS `item_ID`,
        NULL AS `user_ID`,
        `sq`.`datetime_start` AS `datetime_period_occurrence_start`,
        `sq`.`datetime_end` AS `datetime_period_occurrence_end`,
        CAST(`sq`.`datetime_start` AS DATE) AS `date`,
        CAST(`sq`.`datetime_start` AS TIME) AS `time_start`,
        CAST(`sq`.`datetime_end` AS TIME) AS `time_end`,
        'A' AS `period_group_type`,
        0 AS `period_group_priority`,
        NULL AS `period_group_id`
    FROM
        `wp_cb2_view_sequence_date` `sq` 
    UNION ALL SELECT 
        `po`.`ID` AS `ID`,
        `po`.`post_author` AS `post_author`,
        `po`.`post_date` AS `post_date`,
        `po`.`post_date_gmt` AS `post_date_gmt`,
        `po`.`post_content` AS `post_content`,
        `po`.`post_title` AS `post_title`,
        `po`.`post_excerpt` AS `post_excerpt`,
        `po`.`post_status` AS `post_status`,
        `po`.`comment_status` AS `comment_status`,
        `po`.`ping_status` AS `ping_status`,
        `po`.`post_password` AS `post_password`,
        `po`.`post_name` AS `post_name`,
        `po`.`to_ping` AS `to_ping`,
        `po`.`pinged` AS `pinged`,
        `po`.`post_modified` AS `post_modified`,
        `po`.`post_modified_gmt` AS `post_modified_gmt`,
        `po`.`post_content_filtered` AS `post_content_filtered`,
        `po`.`post_parent` AS `post_parent`,
        `po`.`guid` AS `guid`,
        `po`.`menu_order` AS `menu_order`,
        `po`.`post_type` AS `post_type`,
        `po`.`post_mime_type` AS `post_mime_type`,
        `po`.`comment_count` AS `comment_count`,
        `po`.`period_id` AS `period_id`,
        `po`.`recurrence_index` AS `recurrence_index`,
        `po`.`timeframe_ID` AS `timeframe_ID`,
        `po`.`location_ID` AS `location_ID`,
        `po`.`item_ID` AS `item_ID`,
        `po`.`user_ID` AS `user_ID`,
        `po`.`datetime_period_occurrence_start` AS `datetime_period_occurrence_start`,
        `po`.`datetime_period_occurrence_end` AS `datetime_period_occurrence_end`,
        CAST(`sq`.`datetime_start` AS DATE) AS `date`,
        IF((`po`.`datetime_period_occurrence_start` <= `sq`.`datetime_start`),
            TIME '00:00:00',
            CAST(`po`.`datetime_period_occurrence_start` AS TIME)) AS `time_start`,
        IF((`po`.`datetime_period_occurrence_end` >= `sq`.`datetime_end`),
            TIME '23:59:59',
            CAST(`po`.`datetime_period_occurrence_end` AS TIME)) AS `time_end`,
        'G' AS `period_group_type`,
        1 AS `period_group_priority`,
        `pgp`.`period_group_id` AS `period_group_id`
    FROM
        ((((`wp_cb2_view_periodoccurrence_posts` `po`
        JOIN `wp_cb2_periods` `p` ON ((`po`.`period_id` = `p`.`period_id`)))
        JOIN `wp_cb2_period_group_period` `pgp` ON ((`pgp`.`period_id` = `p`.`period_id`)))
        JOIN `wp_cb2_global_period_groups` `ip` ON ((`ip`.`period_group_id` = `pgp`.`period_group_id`)))
        JOIN `wp_cb2_view_sequence_date` `sq` ON (((`po`.`datetime_period_occurrence_start` <= `sq`.`datetime_end`)
            AND (`po`.`datetime_period_occurrence_end` >= `sq`.`datetime_start`)))) 
    UNION ALL SELECT 
        `po`.`ID` AS `ID`,
        `po`.`post_author` AS `post_author`,
        `po`.`post_date` AS `post_date`,
        `po`.`post_date_gmt` AS `post_date_gmt`,
        `po`.`post_content` AS `post_content`,
        `po`.`post_title` AS `post_title`,
        `po`.`post_excerpt` AS `post_excerpt`,
        `po`.`post_status` AS `post_status`,
        `po`.`comment_status` AS `comment_status`,
        `po`.`ping_status` AS `ping_status`,
        `po`.`post_password` AS `post_password`,
        `po`.`post_name` AS `post_name`,
        `po`.`to_ping` AS `to_ping`,
        `po`.`pinged` AS `pinged`,
        `po`.`post_modified` AS `post_modified`,
        `po`.`post_modified_gmt` AS `post_modified_gmt`,
        `po`.`post_content_filtered` AS `post_content_filtered`,
        `po`.`post_parent` AS `post_parent`,
        `po`.`guid` AS `guid`,
        `po`.`menu_order` AS `menu_order`,
        `po`.`post_type` AS `post_type`,
        `po`.`post_mime_type` AS `post_mime_type`,
        `po`.`comment_count` AS `comment_count`,
        `po`.`period_id` AS `period_id`,
        `po`.`recurrence_index` AS `recurrence_index`,
        `po`.`timeframe_ID` AS `timeframe_ID`,
        `po`.`location_ID` AS `location_ID`,
        `po`.`item_ID` AS `item_ID`,
        `po`.`user_ID` AS `user_ID`,
        `po`.`datetime_period_occurrence_start` AS `datetime_period_occurrence_start`,
        `po`.`datetime_period_occurrence_end` AS `datetime_period_occurrence_end`,
        CAST(`sq`.`datetime_start` AS DATE) AS `date`,
        IF((`po`.`datetime_period_occurrence_start` <= `sq`.`datetime_start`),
            TIME '00:00:00',
            CAST(`po`.`datetime_period_occurrence_start` AS TIME)) AS `time_start`,
        IF((`po`.`datetime_period_occurrence_end` >= `sq`.`datetime_end`),
            TIME '23:59:59',
            CAST(`po`.`datetime_period_occurrence_end` AS TIME)) AS `time_end`,
        'L' AS `period_group_type`,
        2 AS `period_group_priority`,
        `pgp`.`period_group_id` AS `period_group_id`
    FROM
        ((((`wp_cb2_view_periodoccurrence_posts` `po`
        JOIN `wp_cb2_periods` `p` ON ((`po`.`period_id` = `p`.`period_id`)))
        JOIN `wp_cb2_period_group_period` `pgp` ON ((`pgp`.`period_id` = `p`.`period_id`)))
        JOIN `wp_cb2_location_period_groups` `ip` ON ((`ip`.`period_group_id` = `pgp`.`period_group_id`)))
        JOIN `wp_cb2_view_sequence_date` `sq` ON (((`po`.`datetime_period_occurrence_start` <= `sq`.`datetime_end`)
            AND (`po`.`datetime_period_occurrence_end` >= `sq`.`datetime_start`)))) 
    UNION ALL SELECT 
        `po`.`ID` AS `ID`,
        `po`.`post_author` AS `post_author`,
        `po`.`post_date` AS `post_date`,
        `po`.`post_date_gmt` AS `post_date_gmt`,
        `po`.`post_content` AS `post_content`,
        `po`.`post_title` AS `post_title`,
        `po`.`post_excerpt` AS `post_excerpt`,
        `po`.`post_status` AS `post_status`,
        `po`.`comment_status` AS `comment_status`,
        `po`.`ping_status` AS `ping_status`,
        `po`.`post_password` AS `post_password`,
        `po`.`post_name` AS `post_name`,
        `po`.`to_ping` AS `to_ping`,
        `po`.`pinged` AS `pinged`,
        `po`.`post_modified` AS `post_modified`,
        `po`.`post_modified_gmt` AS `post_modified_gmt`,
        `po`.`post_content_filtered` AS `post_content_filtered`,
        `po`.`post_parent` AS `post_parent`,
        `po`.`guid` AS `guid`,
        `po`.`menu_order` AS `menu_order`,
        `po`.`post_type` AS `post_type`,
        `po`.`post_mime_type` AS `post_mime_type`,
        `po`.`comment_count` AS `comment_count`,
        `po`.`period_id` AS `period_id`,
        `po`.`recurrence_index` AS `recurrence_index`,
        `po`.`timeframe_ID` AS `timeframe_ID`,
        `po`.`location_ID` AS `location_ID`,
        `po`.`item_ID` AS `item_ID`,
        `po`.`user_ID` AS `user_ID`,
        `po`.`datetime_period_occurrence_start` AS `datetime_period_occurrence_start`,
        `po`.`datetime_period_occurrence_end` AS `datetime_period_occurrence_end`,
        CAST(`sq`.`datetime_start` AS DATE) AS `date`,
        IF((`po`.`datetime_period_occurrence_start` <= `sq`.`datetime_start`),
            TIME '00:00:00',
            CAST(`po`.`datetime_period_occurrence_start` AS TIME)) AS `time_start`,
        IF((`po`.`datetime_period_occurrence_end` >= `sq`.`datetime_end`),
            TIME '23:59:59',
            CAST(`po`.`datetime_period_occurrence_end` AS TIME)) AS `time_end`,
        'I' AS `period_group_type`,
        3 AS `period_group_priority`,
        `pgp`.`period_group_id` AS `period_group_id`
    FROM
        ((((`wp_cb2_view_periodoccurrence_posts` `po`
        JOIN `wp_cb2_periods` `p` ON ((`po`.`period_id` = `p`.`period_id`)))
        JOIN `wp_cb2_period_group_period` `pgp` ON ((`pgp`.`period_id` = `p`.`period_id`)))
        JOIN `wp_cb2_timeframe_period_groups` `ip` ON ((`ip`.`period_group_id` = `pgp`.`period_group_id`)))
        JOIN `wp_cb2_view_sequence_date` `sq` ON (((`po`.`datetime_period_occurrence_start` <= `sq`.`datetime_end`)
            AND (`po`.`datetime_period_occurrence_end` >= `sq`.`datetime_start`)))) 
    UNION ALL SELECT 
        `po`.`ID` AS `ID`,
        `po`.`post_author` AS `post_author`,
        `po`.`post_date` AS `post_date`,
        `po`.`post_date_gmt` AS `post_date_gmt`,
        `po`.`post_content` AS `post_content`,
        `po`.`post_title` AS `post_title`,
        `po`.`post_excerpt` AS `post_excerpt`,
        `po`.`post_status` AS `post_status`,
        `po`.`comment_status` AS `comment_status`,
        `po`.`ping_status` AS `ping_status`,
        `po`.`post_password` AS `post_password`,
        `po`.`post_name` AS `post_name`,
        `po`.`to_ping` AS `to_ping`,
        `po`.`pinged` AS `pinged`,
        `po`.`post_modified` AS `post_modified`,
        `po`.`post_modified_gmt` AS `post_modified_gmt`,
        `po`.`post_content_filtered` AS `post_content_filtered`,
        `po`.`post_parent` AS `post_parent`,
        `po`.`guid` AS `guid`,
        `po`.`menu_order` AS `menu_order`,
        `po`.`post_type` AS `post_type`,
        `po`.`post_mime_type` AS `post_mime_type`,
        `po`.`comment_count` AS `comment_count`,
        `po`.`period_id` AS `period_id`,
        `po`.`recurrence_index` AS `recurrence_index`,
        `po`.`timeframe_ID` AS `timeframe_ID`,
        `po`.`location_ID` AS `location_ID`,
        `po`.`item_ID` AS `item_ID`,
        `po`.`user_ID` AS `user_ID`,
        `po`.`datetime_period_occurrence_start` AS `datetime_period_occurrence_start`,
        `po`.`datetime_period_occurrence_end` AS `datetime_period_occurrence_end`,
        CAST(`sq`.`datetime_start` AS DATE) AS `date`,
        IF((`po`.`datetime_period_occurrence_start` <= `sq`.`datetime_start`),
            TIME '00:00:00',
            CAST(`po`.`datetime_period_occurrence_start` AS TIME)) AS `time_start`,
        IF((`po`.`datetime_period_occurrence_end` >= `sq`.`datetime_end`),
            TIME '23:59:59',
            CAST(`po`.`datetime_period_occurrence_end` AS TIME)) AS `time_end`,
        'U' AS `period_group_type`,
        4 AS `period_group_priority`,
        `pgp`.`period_group_id` AS `period_group_id`
    FROM
        ((((`wp_cb2_view_periodoccurrence_posts` `po`
        JOIN `wp_cb2_periods` `p` ON ((`po`.`period_id` = `p`.`period_id`)))
        JOIN `wp_cb2_period_group_period` `pgp` ON ((`pgp`.`period_id` = `p`.`period_id`)))
        JOIN `wp_cb2_timeframe_user_period_groups` `ip` ON ((`ip`.`period_group_id` = `pgp`.`period_group_id`)))
        JOIN `wp_cb2_view_sequence_date` `sq` ON (((`po`.`datetime_period_occurrence_start` <= `sq`.`datetime_end`)
            AND (`po`.`datetime_period_occurrence_end` >= `sq`.`datetime_start`))));
